---
- name: Make sure yum.repos.d exists
  sudo: yes
  tags: repos
  file: "path=/tmp/repo_rpms state=directory"

- name: Install the GPG Keys
  sudo: yes
  tags: repos
  get_url: url={{ item.value[0].gpgurl }} dest=/etc/pki/rpm-gpg/ mode=0644
  with_dict: repositories

- name: Install the repositories
  sudo: yes
  tags: repos
  template: "src=repo.j2 dest=/etc/yum.repos.d/{{ item.key }}.repo"
  with_dict: repositories
